# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "gradle"
    schedule:
      interval: "weekly"

  - directory: "/charts"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "helm"
    schedule:
      interval: "weekly"

  - directory: "/rest"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "prom-client"
        versions: [">=15.0.0"]
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/rest/monitoring"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/rest/check-state-proof"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/rosetta"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "gomod"
    schedule:
      interval: "weekly"

  - directory: "/tools/traffic-replay/log-downloader"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/tools/mirror-report"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
