# SPDX-License-Identifier: Apache-2.0

hiero:
  mirror:
    grpc:
      db:
        host: 127.0.0.1
        name: mirror_node
        password: mirror_grpc_pass
        port: 5432
        sslMode: DISABLE
        statementTimeout: 10000
        username: mirror_grpc
      port: 5600
grpc:
  server:
    enableKeepAlive: true
    keepAliveTime: 5m
    permitKeepAliveTime: 90s
    port: ${hiero.mirror.grpc.port}
logging:
  level:
    root: warn
    org.hiero.mirror.grpc: info
    io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler: error
    org.hibernate.orm.deprecation: error # Suppress hibernate.dialect warnings
    # io.grpc: debug
    # org.hibernate.SQL: debug
    # org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: "%clr(%date{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSS}, UTC}Z){faint} %clr(${LOG_LEVEL_PATTERN:%5level}) %clr(%thread){magenta} %clr(%logger{20}){cyan} %m %exception%n"
management:
  endpoint:
    health:
      group:
        liveness:
          include: ping
        readiness:
          include: db, grpc, grpcChannel, ping, redis
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        step: 60s
server:
  compression:
    enabled: true
  http2:
    enabled: true
  max-http-request-header-size: 2KB
  port: 8081
  shutdown: graceful
spring:
  application:
    name: grpc
  datasource:
    name: ${hiero.mirror.grpc.db.name}
    password: ${hiero.mirror.grpc.db.password}
    url: jdbc:postgresql://${hiero.mirror.grpc.db.host}:${hiero.mirror.grpc.db.port}/${hiero.mirror.grpc.db.name}?options=-c%20statement_timeout=${hiero.mirror.grpc.db.statementTimeout}
    username: ${hiero.mirror.grpc.db.username}
    hikari:
      connection-timeout: 3000
      data-source-properties:
        idle_in_transaction_session_timeout: "30000"
        lock_timeout: "10000"
        sslmode: ${hiero.mirror.grpc.db.sslMode}
        tcpKeepAlive: true
      maximum-pool-size: 50
      minimum-idle: 4
      validation-timeout: 3000
  jpa:
    database: PostgreSQL
  lifecycle:
    timeout-per-shutdown-phase: 40s
  redis:
    lettuce:
      cluster:
        refresh:
          period: 60s
    timeout: 5s
