# SPDX-License-Identifier: Apache-2.0

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: monitor

alertmanager:
  inhibitRules:
    enabled: false

    InhibitHandleLatencyAlertWhenHighPublishLatency:
      enabled: true
      matches:
        - sourceMatch:
            - name: alertname
              value: MonitorPublishLatency
          targetMatch:
            - name: alertname
              value: MonitorPublishToHandleLatency
          equal:
            - namespace
            - pod

    InhibitAllWhenPodIssues:
      enabled: true
      matches:
        - sourceMatch:
            - name: area
              value: resource
          targetMatch:
            - name: application
              value: monitor
          equal:
            - namespace
            - pod

    InhibitPublishAlertsWhenPublishStopped:
      enabled: true
      matches:
        - sourceMatch:
            - name: alertname
              value: MonitorPublishStopped
          targetMatch:
            - name: mode
              value: publish
          equal:
            - namespace
            - pod

annotations: {}

config: {}

# Environment variables to add to the container. The value can either be a string or an EnvVarSource. Evaluated as a template.
env:
  SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/usr/etc/hiero/"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  # FOO:
  #   valueFrom:
  #     secretKeyRef:
  #       name: '{{ .Release.Name }}-custom'
  #       key: BAR

# Add config maps or secrets as environment variables. Evaluated as a template.
envFrom: []
# - secretRef:
#     name: '{{ .Release.Name }}-env'

fullnameOverride: ""

global:
  config: {}
  env: {}
  image: {}
  namespaceOverride: ""
  podAnnotations: {}

image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: gcr.io
  repository: mirrornode/hedera-mirror-monitor
  tag: ""  # Defaults to the chart's app version

ingress:
  annotations: {}
  enabled: true
  hosts:
    - host: ""
      paths: ["/actuator/health/cluster"]
  tls:
    enabled: false
    secretName: ""

labels: {}

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 2

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

priorityClassName: ""

prometheusRules:
  enabled: false
  MonitorHighCPU:
    annotations:
      description: "{{ $labels.namespace }}/{{ $labels.pod }} CPU usage reached {{ $value | humanizePercentage }}"
      summary: "Mirror Monitor CPU usage exceeds 80%"
    enabled: true
    expr: sum(process_cpu_usage{application="monitor"}) by (namespace, pod) / sum(system_cpu_count{application="monitor"}) by (namespace, pod) > 0.8
    for: 5m
    labels:
      severity: critical
      application: monitor
      area: resource

  MonitorHighMemory:
    annotations:
      description: "{{ $labels.namespace }}/{{ $labels.pod }} memory usage reached {{ $value | humanizePercentage }}"
      summary: "Mirror Monitor memory usage exceeds 80%"
    enabled: true
    expr: sum(jvm_memory_used_bytes{application="monitor"}) by (namespace, pod) / sum(jvm_memory_max_bytes{application="monitor"}) by (namespace, pod) > 0.8
    for: 5m
    labels:
      severity: critical
      application: monitor
      area: resource

  MonitorLogErrors:
    annotations:
      description: "Logs for {{ $labels.namespace }}/{{ $labels.pod }} have reached {{ $value }} error messages/s in a 3m period"
      summary: "High rate of log errors"
    enabled: true
    expr: sum(increase(logback_events_total{application="monitor", level="error"}[2m])) by (namespace, pod) >= 2
    for: 3m
    labels:
      severity: critical
      application: monitor

  MonitorNoPodsReady:
    annotations:
      description: "No monitor instances are currently running in {{ $labels.namespace }}"
      summary: No monitor instances running
    enabled: true
    expr: sum(kube_pod_status_ready{pod=~".*-monitor-.*",condition="true"}) by (namespace) < 1
    for: 2m
    labels:
      severity: critical
      application: monitor
      area: resource

  MonitorPublishErrors:
    annotations:
      description: "Averaging {{ $value | humanizePercentage }} error rate publishing '{{ $labels.scenario }}' scenario from {{ $labels.namespace }}/{{ $labels.pod }}"
      summary: "Publish error rate exceeds 50%"
    enabled: true
    expr: sum(rate(hiero_mirror_monitor_publish_submit_seconds_count{application="monitor",status!="SUCCESS"}[2m])) by (namespace, pod, scenario) / sum(rate(hiero_mirror_monitor_publish_submit_seconds_count{application="monitor"}[2m])) by (namespace, pod, scenario) > 0.50
    for: 3m
    labels:
      severity: critical
      application: monitor
      mode: publish

  MonitorPublishLatency:
    annotations:
      description: "Averaging {{ $value | humanizeDuration }} publish latency for '{{ $labels.scenario }}' scenario for {{ $labels.namespace }}/{{ $labels.pod }}"
      summary: "Publish latency exceeds 7s"
    enabled: true
    expr: sum(rate(hiero_mirror_monitor_publish_submit_seconds_sum{application="monitor"}[2m])) by (namespace, pod, scenario) / sum(rate(hiero_mirror_monitor_publish_submit_seconds_count{application="monitor"}[2m])) by (namespace, pod, scenario) > 7
    for: 5m
    labels:
      severity: warning
      application: monitor
      mode: publish

  MonitorPublishPlatformNotActive:
    annotations:
      description: "Averaging {{ $value | humanizePercentage }} PLATFORM_NOT_ACTIVE or UNAVAILABLE errors while attempting to publish in {{ $labels.namespace }}"
      summary: "Platform is not active"
    enabled: true
    expr: sum(rate(hiero_mirror_monitor_publish_submit_seconds_count{application="monitor",status=~"(PLATFORM_NOT_ACTIVE|UNAVAILABLE)"}[2m])) by (namespace) / sum(rate(hiero_mirror_monitor_publish_submit_seconds_count{application="monitor"}[2m])) by (namespace) > 0.33
    for: 1m
    labels:
      application: monitor
      mode: publish
      severity: warning

  MonitorPublishStopped:
    annotations:
      description: "Publish TPS dropped to {{ $value }} for '{{ $labels.scenario }}' scenario for {{ $labels.namespace }}/{{ $labels.pod }}"
      summary: "Publishing stopped"
    enabled: true
    expr: (sum(rate(hiero_mirror_monitor_publish_submit_seconds_sum{application="monitor"}[2m])) by (namespace, pod, scenario) / sum(rate(hiero_mirror_monitor_publish_submit_seconds_count{application="monitor"}[2m])) by (namespace, pod, scenario) > 0 or on() vector(0)) <= 0
    for: 2m
    labels:
      severity: critical
      application: monitor
      mode: publish

  MonitorPublishToHandleLatency:
    annotations:
      description: "Averaging {{ $value | humanizeDuration }} transaction latency for '{{ $labels.scenario }}' scenario for {{ $labels.namespace }}/{{ $labels.pod }}"
      summary: "Submit to transaction being handled latency exceeds 11s"
    enabled: true
    expr: sum(rate(hiero_mirror_monitor_publish_handle_seconds_sum{application="monitor"}[5m])) by (namespace, pod, scenario) / sum(rate(hiero_mirror_monitor_publish_handle_seconds_count{application="monitor"}[5m])) by (namespace, pod, scenario) > 11
    for: 5m
    labels:
      severity: warning
      application: monitor
      mode: publish

  MonitorSubscribeLatency:
    annotations:
      description: "Latency averaging {{ $value | humanizeDuration }} for '{{ $labels.scenario }}' #{{ $labels.subscriber }} scenario for {{ $labels.namespace }}/{{ $labels.pod }}"
      summary: "End to end latency exceeds 14s"
    enabled: true
    expr: sum(rate(hiero_mirror_monitor_subscribe_e2e_seconds_sum{application="monitor"}[2m])) by (namespace, pod, scenario, subscriber) / sum(rate(hiero_mirror_monitor_subscribe_e2e_seconds_count{application="monitor"}[2m])) by (namespace, pod, scenario, subscriber) > 14
    for: 5m
    labels:
      severity: critical
      application: monitor

  MonitorSubscribeStopped:
    annotations:
      description: "TPS dropped to {{ $value }} for '{{ $labels.scenario }}' #{{ $labels.subscriber }} scenario for {{ $labels.namespace }}/{{ $labels.pod }}"
      summary: "Subscription stopped"
    enabled: true
    expr: (sum(rate(hiero_mirror_monitor_subscribe_e2e_seconds_sum{application="monitor"}[2m])) by (namespace, pod, subscriber, scenario) / sum(rate(hiero_mirror_monitor_subscribe_e2e_seconds_count{application="monitor"}[2m])) by (namespace, pod, subscriber, scenario) > 0 or on() vector(0)) <= 0
    for: 2m
    labels:
      severity: critical
      application: monitor

rbac:
  enabled: true

readinessProbe:
  failureThreshold: 5
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 60
  timeoutSeconds: 2

replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi

revisionHistoryLimit: 3

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

service:
  annotations: {}
  port: 80
  type: ClusterIP

serviceAccount:
  create: true
  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

serviceMonitor:
  enabled: false
  interval: 30s

terminationGracePeriodSeconds: 60

tolerations: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 10%
    maxUnavailable: 25%

# Volumes to add to the container. The key is the volume name and the value is the volume mount definition. The same keys should also appear in volumes below.
volumeMounts:
  config:
    mountPath: /usr/etc/hiero

# Volume mounts to add to the container. The key is the volume name and the value is the volume definition. Evaluated as a template.
volumes:
  config:
    secret:
      defaultMode: 420
      secretName: '{{ include "hedera-mirror-monitor.fullname" . }}'
