# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
appVersion: 0.144.0-rc1
dependencies:
  - alias: minio
    condition: minio.enabled
    name: minio
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 17.0.21
  - name: loki
    condition: loki.enabled
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
  - condition: prometheus-adapter.enabled
    name: prometheus-adapter
    repository: oci://ghcr.io/prometheus-community/charts
    version: 4.14.1
  - alias: prometheus
    condition: prometheus.enabled
    name: kube-prometheus-stack
    repository: oci://ghcr.io/prometheus-community/charts
    version: 70.4.2
  - name: promtail
    condition: promtail.enabled
    version: 6.16.6
    repository: oci://ghcr.io/grafana/helm-charts
  - alias: stackgres
    condition: stackgres.enabled
    name: stackgres-operator
    repository: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
    version: 1.17.0
  - condition: traefik.enabled
    name: traefik
    repository: oci://ghcr.io/traefik/helm
    version: 35.0.0
  - alias: zfs
    condition: zfs.enabled
    name: openebs
    repository: https://openebs.github.io/openebs
    version: 4.3.3
description: Mirror Node common components installed globally for use across namespaces
home: https://github.com/hiero-ledger/hiero-mirror-node
icon: https://camo.githubusercontent.com/cca6b767847bb8ca5c7059481ba13a5fc81c5938/68747470733a2f2f7777772e6865646572612e636f6d2f6c6f676f2d6361706974616c2d686261722d776f72646d61726b2e6a7067
maintainers:
  - name: Mirror Node Team
    email: mirrornode@hedera.com
name: hedera-mirror-common
version: 0.144.0-rc1
