# SPDX-License-Identifier: Apache-2.0

hiero:
  mirror:
    rest:
      metrics:
        enabled: false
      query:
        maxRepeatedQueryParameters: 8
      redis:
        enabled: false
        maxRetriesPerRequest: 10
